# permissions for end users to view messages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: message-viewer-role
rules:
- apiGroups:
  - hello.bells17.io
  resources:
  - messages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hello.bells17.io
  resources:
  - messages/status
  verbs:
  - get
