
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - limit.bells17.io
  resources:
  - ssls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - limit.bells17.io
  resources:
  - ssls/finalizers
  verbs:
  - update
- apiGroups:
  - limit.bells17.io
  resources:
  - ssls/status
  verbs:
  - get
  - patch
  - update
